### ISSUE TITLE
Support unsigned types

### ISSUE THREAD

**Issue by amerkoleci** [jkoritzinsky/SharpGenTools#42] opened 2018-03-02 19:44 UTC
While fixing an issue with SharpDX I saw i cannot map "ushort" type for enum:
<map enum="XINPUT_GAMEPAD_BUTTON_FLAGS" name="GamepadButtonFlags" flags="true" none="true" type="ushort"/>

**Comment by jkoritzinsky** [comment] 2018-03-02 19:52
You should be able to set the underlying type of the enumeration to ``System.UInt16``. SharpGenTools doesn't support the shortened C# keywords for the type names.

**Comment by amerkoleci** [comment] 2018-03-02 19:55
No problem, maybe you can add the shortened keyword support.

Thanks

**Comment by amerkoleci** [comment] 2018-03-02 19:59
Tried and System.UInt16 does not work as well, it says that only int, byte or short is supported for enum types.

**Comment by jkoritzinsky** [comment] 2018-03-02 20:01
Can you copy the mapping rule you're using and paste in in this thread? I think I remember now where the issue you're hitting is but I want to be sure.

**Comment by jkoritzinsky** [comment] 2018-03-02 20:03
I think the issue is here:

https://github.com/jkoritzinsky/SharpGenTools/blob/371d7ced16f5cce8514c8038088fe948b740d30d/SharpGen/Transform/EnumTransform.cs#L81-L96

This follows a different code-path than what everything else uses for resolving types.

**Closed** 2018-04-24 18:46 UTC
